version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # Esta linea de abajo hace que cada vez que se reinicie se inicia solo
    # restart: always
    ports:
      - 8080:80
    environment:
    # Public Networking
      - PMA_HOST=yamabiko.proxy.rlwy.net
      - PMA_PORT=29522
      # MYSQLUSER
      - PMA_USER=root
      # MYSQL_ROOT_PASSWORD
      - PMA_PASSWORD=HwHIRXdQHQHmqNwoNOrSuolhXHmKGhLB